---
language: node_js
node_js:
  - "8"

branches:
  only:
    - master

matrix:
  include:
  - name: "npm"
    install:
      - npm link
    script:
      - cd ../
      - npm init ember-app test-app
      - cd test-app
      - "node_modules/.bin/ember -v | grep -q 'ember-cli: 3.6'"
  - name: "Yarn"
    install:
      - yarn
      - yarn link
    script:
      - cd ../
      - create-ember-app test-app # Cannot use yarn create because of https://github.com/yarnpkg/yarn/issues/6862
      - cd test-app
      - "node_modules/.bin/ember -v | grep -q 'ember-cli: 3.6'"
