---
language: node_js
node_js:
  - "8"

branches:
  only:
    - master

matrix:
  include:
  - name: "npm"
    install:
      - npm link
    script:
      - cd ../
      - npm init ember-app test-app
      - cd test-app
      - "export CURRENT_VERSION=`curl -H \"Authorization: token $GITHUB_TOKEN\" https://api.github.com/repos/ember-cli/ember-cli/releases/latest | jq '.tag_name' | grep -Po '\\d+\\.\\d+\\.\\d+'`"
      - echo $CURRENT_VERSION
      - node_modules/.bin/ember -v
      - "node_modules/.bin/ember -v | grep -q \"ember-cli: $CURRENT_VERSION\""
  - name: "Yarn"
    install:
      - yarn
      - yarn link
    script:
      - cd ../
      - create-ember-app test-app # Cannot use yarn create because of https://github.com/yarnpkg/yarn/issues/6862
      - cd test-app
      - "export CURRENT_VERSION=`curl -H \"Authorization: token $GITHUB_TOKEN\" https://api.github.com/repos/ember-cli/ember-cli/releases/latest | jq '.tag_name' | grep -Po '\\d+\\.\\d+\\.\\d+'`"
      - echo $CURRENT_VERSION
      - node_modules/.bin/ember -v
      - "node_modules/.bin/ember -v | grep -q \"ember-cli: $CURRENT_VERSION\""
